config/routes.rb
Rails.application.routes.draw do
	root 'photo_albums#index'
  resources :photo_albums do
	  resources :photos, shallow: true
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
	mount_uploader :file, ImageUploader
  belongs_to :photo_album, counter_cache: true

end

app/models/photo_album.rb
class PhotoAlbum < ApplicationRecord
	mount_uploader :cover_image, ImageUploader
	has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photo_albums_controller.rb
class PhotoAlbumsController < ApplicationController
  before_action :set_photo_album, only: [:show, :edit, :update, :destroy]

  # GET /photo_albums
  # GET /photo_albums.json
  def index
    @photo_albums = PhotoAlbum.all
    @photo_album = PhotoAlbum.new
  end

  # GET /photo_albums/1
  # GET /photo_albums/1.json
  def show
  end

  # GET /photo_albums/new
  def new
    @photo_album = PhotoAlbum.new
  end

  # GET /photo_albums/1/edit
  def edit
  end

  # POST /photo_albums
  # POST /photo_albums.json
  def create
    @photo_album = PhotoAlbum.new(photo_album_params)

    respond_to do |format|
      if @photo_album.save
        format.html { redirect_to @photo_album, notice: 'Photo album was successfully created.' }
        format.json { render :show, status: :created, location: @photo_album }
      else
        format.html { render :new }
        format.json { render json: @photo_album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photo_albums/1
  # PATCH/PUT /photo_albums/1.json
  def update
    respond_to do |format|
      if @photo_album.update(photo_album_params)
        format.html { redirect_to @photo_album, notice: 'Photo album was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo_album }
      else
        format.html { render :edit }
        format.json { render json: @photo_album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photo_albums/1
  # DELETE /photo_albums/1.json
  def destroy
    @photo_album.destroy
    respond_to do |format|
      format.html { redirect_to photo_albums_url, notice: 'Photo album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo_album
      @photo_album = PhotoAlbum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_album_params
      params.require(:photo_album).permit(:title, :description, :cover_image)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo_album = PhotoAlbum.find(params[:photo_album_id])
    @photo = Photo.new
    @photo.photo_album = @photo_album
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo_album = PhotoAlbum.find(params[:photo_album_id])
    photo_params[:file].each do |photo_file|
      @photo = Photo.create(file: photo_file, photo_album: @photo_album)
    end
    redirect_to root_path
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(file: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_albums_helper.rb
module PhotoAlbumsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoShare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photo_albums/_form.html.erb
<%= form_with(model: photo_album, local: true) do |form| %>
  <% if photo_album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo_album.errors.count, "error") %> prohibited this photo_album from being saved:</h2>

      <ul>
      <% photo_album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :photo_album_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :photo_album_description %>
  </div>

  <div class="field">
    <%= form.label :cover_image %>
    <%= form.file_field :cover_image, id: :photo_album_cover_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photo_albums/edit.html.erb
<h1>Editing Photo Album</h1>

<%= render 'form', photo_album: @photo_album %>

<%= link_to 'Show', @photo_album %> |
<%= link_to 'Back', photo_albums_path %>

app/views/photo_albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photo Albums</h1>
<%= render 'form', photo_album: @photo_album %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Cover image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photo_albums.each do |photo_album| %>
      <tr>
        <td><%= photo_album.title %></td>
        <td><%= photo_album.description %></td>
        <td><%= image_tag photo_album.cover_image.url %></td>
        <td><%= link_to 'Show', photo_album %></td>
        <td><%= link_to 'Edit', edit_photo_album_path(photo_album) %></td>
        <td><%= link_to 'Destroy', photo_album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo Album', new_photo_album_path %>

app/views/photo_albums/new.html.erb
<h1>New Photo Album</h1>

<%= render 'form', photo_album: @photo_album %>

<%= link_to 'Back', photo_albums_path %>

app/views/photo_albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @photo_album.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @photo_album.description %>
</p>

<p>
  <strong>Cover image:</strong>
  <%= @photo_album.cover_image %>
</p>

<%= link_to 'Add Photo', new_photo_album_photo_path(@photo_album) %> |
<%= link_to 'Edit', edit_photo_album_path(@photo_album) %> |
<%= link_to 'Back', photo_albums_path %>
<% @photo_album.photos.each do |photo| %>
	<p>
		<%= image_tag photo.file.url %>
	</p>
<% end %>

app/views/photos/_form.html.erb
<%= form_with(model: [@photo_album, photo], local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file, multiple: true, id: :photo_file %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th>File</th>
      <th>Photo album</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.file %></td>
        <td><%= photo.photo_album %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File:</strong>
  <%= @photo.file %>
</p>

<p>
  <strong>Photo album:</strong>
  <%= @photo.photo_album %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%#= link_to 'Back', photos_path %>